### ISSUE TITLE
Doesn't on on NFS:MW

### ISSUE THREAD

**Issue by Electric1447** [Electry/NoPowerLimitsVita#1]
Doesn't work on Need For Speed Most Wanted (PCSB00183)

**Comment by Electry** [comment]
I tested PCSB00183 and it does in fact work.
Make sure you installed correctly and rebooted afterwards.

![ezgif-2-d20774e9f396](https://user-images.githubusercontent.com/12598379/66704423-34ab0080-ed1c-11e9-8564-affe19ce320d.gif)
