### ISSUE TITLE
Question about this plugin 

### ISSUE THREAD

**Issue by Doredialilligan** [Electry/NoPowerLimitsVita#2]
After reading the readme, I'm not very sure what this plugin does exactly. 
So I think that with it we gain extra power for some games that use some power modes.
Is this correct? :)

**Comment by Electry** [comment]
It allows you to set 100% brightness in all games (where previously the slider reverted back to 80% when you moved it past 80%).

It also gets rid of this, so wifi stays on in all games (to allow bg downloads and such).
![image](https://user-images.githubusercontent.com/12598379/66704374-a20a6180-ed1b-11e9-95b7-a3d501535cfa.png)
