### ISSUE TITLE
Project DIVA f/f2nd camera inaccessibility

### ISSUE THREAD

**Issue by EzTell** [Electry/NoPowerLimitsVita#3]
So i found this issue as i was going to launch AR mode in these games after installing a plugin. Official camera app seems to be working fine but camera module is inaccessible from other applications(at least two listed in the topic). Also linking a video showing this: [https://youtu.be/CmTlzzDSl9w](url)

Device: PCH-1000, 3.65 Enso, 32gb via sd2vita as ux0, 16gb via vita memory card as uma0

EDIT: almost forgot to note that in PD F2nd after attemting to launch AR mode all buttons except PS were inactive(could be app bug caued by camera inaccesibility)

**Comment by Electry** [comment]
Ah yes, thanks for reporting.

Give this a try:
[NoPowerLimits.zip](https://github.com/Electry/NoPowerLimitsVita/files/3802250/NoPowerLimits.zip)

**Comment by EzTell** [comment]
Thank you very much, now camera works right as intended while brightness and wlan features are present. Attaching proofs for PD F and PD F2nd:
![2019-11-04-121806](https://user-images.githubusercontent.com/47968474/68096754-ad0d7780-fefe-11e9-8fd1-55139cb1f2d3.png)
![2019-11-04-121148](https://user-images.githubusercontent.com/47968474/68096757-b39bef00-fefe-11e9-8604-3ff407e705f2.png)
